name: Greet User
on: [workflow_dispatch]
jobs:
  greet: 
    runs-on: ubuntu-latest
    steps: 
      - name: greet user
        run: echo "Hello World !!!"
      - name: Bye User
        run: echo "Bye Bye"